### ISSUE TITLE
Feature: Average colour utility method

### ISSUE THREAD

**Issue by renemarc** [tremby/py-lightpack#5]
As a developer, I want to be able to easily read the colour average for all lights in a Lightpack.

**It's done when:**
- The mean RGB value for all lights can be fetched in a single utility method.

**Comment by tremby** [comment]
Just curious as to your use case for this. Is there a reason this should be in the library -- would it be less efficient to have in your application?

**Comment by dobrynski** [comment]
I suspect it is because Home Assistant frowns on putting functionality they see as belonging inside an external library in the components. The component should interface with Home Assistant rather than contain component specific code.

Specifically https://developers.home-assistant.io/docs/en/creating_component_code_review.html.

> 4. Communication with devices/services 
> All API specific code has to be part of a third party library hosted on PyPi. Home Assistant should only interact with objects and not make direct calls to the API.

Not sure if this feature would be included but I suspect they would consider it out of place in the component itself.

**Comment by tremby** [comment]
I don't think I follow. Getting the average colour from the library would be ok, but getting all the colours and then averaging them would not?

I'm just not sure this belongs. Off hand I think it'd be the only method which produces a calculated response rather than just a formatted one.

**Comment by dobrynski** [comment]
You may be right. I hadn't considered that. Curious to hear from @renemarc.

**Comment by renemarc** [comment]
While this logic _could_ reside in the application instead, `getColourAverage()` was meant more as a symmetric method to the existing utility method `setColourToAll()`. So the library would have one method to assign a single colour to all lights at once, and another to read the single calculated colour at once.

**Comment by tremby** [comment]
Yup, this has convinced me. :)

**Comment by renemarc** [comment]
Yay! 😃

**Comment by tremby** [comment]
This is merged. I stripped out your version number changes, and bumped just once after the merges, to v2.2.0.
